In [1]:
import numpy as np

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
arr = np.array([1,2,3])
arr.dtype

dtype('int32')

In [8]:
arr = np.array([1,2,3], dtype=np.float64)
arr.dtype

dtype('float64')

In [9]:
arr[1]

2.0

In [13]:
arr = np.array(range(10))
arr[0::2]

array([0, 2, 4, 6, 8])

In [23]:
arr = np.array(range(100))
rarr = arr[::-1]
rarr

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [37]:
arr = np.array([[0,1,0], [1,0,1], [1, 1, 0], [1, 1, 0], [0,2,1]])

In [35]:
arr.ndim

2

In [39]:
arr.shape

(5, 3)

In [40]:
arr[2, 2]


0


In [42]:
a2 = np.array([
    [[0, 1, 1], [0, 1, 0], [1, 0, 0]],
    [[0, 1, 1], [0, 1, 0], [1, 0,0]],
    [[0, 2, 1], [2, 1, 2], [3,2,1]]])

In [43]:
a2

array([[[0, 1, 1],
        [0, 1, 0],
        [1, 0, 0]],

       [[0, 1, 1],
        [0, 1, 0],
        [1, 0, 0]],

       [[0, 2, 1],
        [2, 1, 2],
        [3, 2, 1]]])

In [47]:
np.array([[0, 1], [2,3]])[:,0]

array([0, 2])

In [48]:
a2[::-1, ::-1, ::-1] # flip a2

array([[[1, 2, 3],
        [2, 1, 2],
        [1, 2, 0]],

       [[0, 0, 1],
        [0, 1, 0],
        [1, 1, 0]],

       [[0, 0, 1],
        [0, 1, 0],
        [1, 1, 0]]])

In [50]:
big_array = np.zeros([5,5,5,5,5])
big_array.shape
big_array[...]

array([[[[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0., 

In [52]:
big_array[0,1,2,...]

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [53]:
big_array[0,1,...,2]

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])